### ISSUE TITLE
'check_port_open' was never awaited

### ISSUE THREAD

**Issue by pikeas** [aio-libs/aiohttp-devtools#199]
OS X 10.12.6, Python 3.6.6, aiohttp 3.3, aiohttp-devtools 0.10.1

runserver raises an exception on ctrl-C:

```
pikeas@27d8f65ec422:~$ adev runserver foo/__main__.py
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^C
Traceback (most recent call last):
  File "/app/.venv/bin/adev", line 11, in <module>
    sys.exit(cli())
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/app/.venv/lib/python3.6/site-packages/aiohttp_devtools/cli.py", line 86, in runserver
    run_app(*_runserver(**active_config))
  File "/app/.venv/lib/python3.6/site-packages/aiohttp_devtools/runserver/main.py", line 47, in runserver
    loop.run_until_complete(check_port_open(config.main_port, loop))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 444, in run_until_complete
    self._check_closed()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'check_port_open' was never awaited
```

**Comment by invisiblefunnel** [comment]
I'm also seeing this warning. Can it be safely ignored?

**Comment by Dreamsorcerer** [comment]
Please try v1.0. Reopen the issue if it is still an issue.
