### ISSUE TITLE
Incorrect behavior if __name__ == '__main__': sys.exit(main())

### ISSUE THREAD

**Issue by Randomneo** [aio-libs/aiohttp-devtools#290]
* **aiohttp-devtools version: 0.13.1**
* **aiohttp version: 3.7.3**
* **python version: 3.9.1**
* **Platform: ubuntu 18.04**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

### Issue Summary

Unable to run this code with `adev runserver --app-factory main`

    import sys
    
    from aiohttp import web
    
    from rainet_access_battle.app import build_routes

    def main():
        app = web.Application()
        app.add_routes([
            web.get('/', hello),
        ])
        web.run_app(app)

    if __name__ == '__main__':
        sys.exit(main())

### Error

    [12:29:02] Starting aux server at http://localhost:8001 ◆                                                                                                                                                        
    [12:29:02] Starting dev server at http://localhost:8000 ●                                                                                                                                                        
    Process Process-1:                                                                                                                                                                                               
    Traceback (most recent call last):                                                                                                                                                                               
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp/web.py", line 508, in run_app
        loop.run_until_complete(main_task)
      File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
        self._check_running()
      File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
        raise RuntimeError('This event loop is already running')
    RuntimeError: This event loop is already running
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp_devtools/runserver/serve.py", line 120, in serve_main_app
        runner = loop.run_until_complete(start_main_app(config, app_factory, loop))
      File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp_devtools/runserver/serve.py", line 131, in start_main_app
        app = await config.load_app(app_factory)
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp_devtools/runserver/config.py", line 171, in load_app
        app = app_factory()
      File "/home/rostyslav/projects/rainet_access_battle/backend/src/main.py", line 11, in main
        web.run_app(app)
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp/web.py", line 512, in run_app
        _cancel_tasks({main_task}, loop)
      File "/home/rostyslav/.virtualenvs/default/lib/python3.9/site-packages/aiohttp/web.py", line 443, in _cancel_tasks
        loop.run_until_complete(
      File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
        self._check_running()
      File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
        raise RuntimeError('This event loop is already running')
    RuntimeError: This event loop is already running

**Comment by Randomneo** [comment]
Got same error with python3.7 and same libs versions.

**Comment by Randomneo** [comment]
--app-factory method must return Application instance. This could be not clear

Should be additional explanation added?
