### ISSUE TITLE
As of 3.10, the *loop* parameter was removed from Event

### ISSUE THREAD

**Issue by Artalus** [aio-libs/aiohttp-devtools#389]
* **aiohttp-devtools version:** 0.13.1
* **aiohttp version:** 3.8.1
* **python version:** 3.10
* **Platform:** windows

### Issue Summary
When using `runserver`, with `Python 3.10` on `Windows`, the following exception occurs:
```
Traceback (most recent call last):
  File "C:\Python\310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\git\aiohttp-queue\venv\Scripts\adev.exe\__main__.py", line 7, in <module>
  File "S:\git\aiohttp-queue\venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "S:\git\aiohttp-queue\venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\aiohttp_devtools\cli.py", line 84, in
runserver
    run_app(*_runserver(**active_config))
  File "S:\git\aiohttp-queue\venv\lib\site-packages\aiohttp_devtools\runserver\main.py", line 56, in runserver
    main_manager = AppTask(config, loop)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\aiohttp_devtools\runserver\watch.py",
line 49, in __init__
    super().__init__(self._config.watch_path, loop)
  File "S:\git\aiohttp-queue\venv\lib\site-packages\aiohttp_devtools\runserver\watch.py",
line 22, in __init__
    self.stopper = asyncio.Event(loop=self._loop)
  File "C:\Python\310\lib\asyncio\locks.py", line 167, in __init__
    super().__init__(loop=loop)
  File "C:\Python\310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary
```

### Steps to reproduce
- copypaste [example from docs](https://docs.aiohttp.org/en/stable/index.html#server-example)
- run `adev runserver server.py`

**Comment by Dreamsorcerer** [comment]
Current release of devtools is broken anyway. Use master or wait until we push a new release (soon, hopefully).

**Comment by Dreamsorcerer** [comment]
Released now. Should be working with 3.10, but the test are failing currently (#376), so let me know if there are any issues.
