### ISSUE TITLE
async_generator object has no attribute lock

### ISSUE THREAD

**Issue by wiryonolau** [aio-libs/aiohttp-devtools#453]
* **aiohttp-devtools version: 1.0-post0**
* **aiohttp version: 3.8.1**
* **python version: 3.8**
* **Platform: Ubuntu 18.04 virtualenv**

### Issue Summary
When stopping dev using ctrl +C, a bunch of error message appear
Currently doesn't break when running

```
task: <Task finished name='Task-4' coro=<_run_app() done, defined at /.env/lib/python3.8/
site-packages/aiohttp/web.py:287> exception=AttributeError("'async_generator' object has no attribute 'lock'")>
Traceback (most recent call last):
  File "/.env/lib/python3.8/site-packages/aiohttp/web.py", line 433, in _run_app
    await runner.cleanup()
  File "/.env/lib/python3.8/site-packages/aiohttp/web_runner.py", line 294, in cleanup
    await self._cleanup_server()
  File "/.env/lib/python3.8/site-packages/aiohttp/web_runner.py", line 381, in _cleanup_server
    await self._app.cleanup()
  File "/.env/lib/python3.8/site-packages/aiohttp/web_app.py", line 432, in cleanup
    await self.on_cleanup.send(self)
  File "/.env/lib/python3.8/site-packages/aiosignal/__init__.py", line 36, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/.env/lib/python3.8/site-packages/aiohttp/web_app.py", line 555, in _on_cleanup
    raise errors[0]
  File "/.env/lib/python3.8/site-packages/aiohttp/web_app.py", line 546, in _on_cleanup
    await it.__anext__()
  File "/.env/lib/python3.8/site-packages/aiohttp_devtools-1.0.post0-py3.8.egg/aiohttp_de
vtools/runserver/watch.py", line 43, in cleanup_ctx
    await self.close(app)
  File "/.env/lib/python3.8/site-packages/aiohttp_devtools-1.0.post0-py3.8.egg/aiohttp_de
vtools/runserver/watch.py", line 133, in close
    await asyncio.gather(super().close(), self._session.close())
  File "/.env/lib/python3.8/site-packages/aiohttp_devtools-1.0.post0-py3.8.egg/aiohttp_de                                                                                    
vtools/runserver/watch.py", line 35, in close
    async with self._awatch.lock:
AttributeError: 'async_generator' object has no attribute 'lock'

```
### Steps to reproduce
Run in dev
KeyboardInterrupt

**Comment by Dreamsorcerer** [comment]
For some reason, I can't reproduce this. Can you provide a complete application that triggers this for you? Also, can you confirm the version of watchgod you have installed?

**Comment by Dreamsorcerer** [comment]
Hmm, so I can see there is a `.lock` in the last version of watchgod: https://github.com/samuelcolvin/watchfiles/blob/watchgod/watchgod/main.py#L94

But, the new `watchfiles` version is just an async generator with no lock attribute. Judging by your traceback, it looks like you've somehow ended up using this new library...

We will want to update to this version shortly, but until then you should try downgrading the watchfiles/watchgod library. Still unclear how you've ended with that version though..

**Comment by wiryonolau** [comment]
it's no longer appear now. Thanks
I'm still using #209 approach
